name: cm_app
description: "Channel Myanmar WebSoup"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 2.4.5
repository: https://github.com/ThanCoder/cm_app

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  than_pkg: ^5.0.0
  t_widgets: ^2.0.2
  flutter_html: ^3.0.0
  t_client: ^0.1.6
  flutter_markdown: ^0.7.7+1
  yaml: ^3.1.3
  cached_network_image: ^3.4.1

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  # dart run change_app_package_name:main [com.new.package.name]
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  # dart run flutter_launcher_icons
  android: "launcher_icon"
  image_path: "assets/logo_2.jpg"
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/lang/
    - assets/test/
    - CHANGELOG.md
    - README.md
    - pubspec.yaml
