name: cm_app
description: "Channel Myanmar WebSoup"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 2.0.0
repository: https://github.com/ThanCoder/cm_app

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  expandable_text: ^2.3.0
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  than_pkg: ^4.5.3
  t_widgets: ^1.5.1
  flutter_html: ^3.0.0
  t_client: ^0.1.6
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  # dart run change_app_package_name:main [com.new.package.name]
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  # dart run flutter_launcher_icons
  android: "launcher_icon"
  image_path: "assets/logo.png"
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/test/
    - CHANGELOG.md
    - README.md
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
